name: student_system_app_v2
description: Student system app with login, profile, timetable, attendance
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  crypto: ^3.0.3
  table_calendar: ^3.0.9
  flutter_email_sender: ^7.0.0
  flutter_local_notifications: ^19.1.0
  mobile_scanner: ^6.0.10
  timezone: ^0.10.1

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
